server:
  port: 8888
spring:
  application:
    name: config-service-demo
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: true
      server:
        git:
          uri: https://github.com/lvning300/config-repo.git
          username:
          password:
          basedir: target/config
eureka:
  instance:
    hostname: ${eureka.client.instance.hostname} #hostname: localhost
    instance-id: ${eureka.client.instance.hostname}:${server.port}
    prefer-ip-address: true # 开启以Ip+端口多方式显示Eureka界面
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/
